package com.bondsales.backend.dao.mapper;

import com.bondsales.backend.dao.entity.Sales;
import java.util.List;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sellid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    Sales selectByPrimaryKey(Long sellid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    List<Sales> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sales record);
}