package com.bondsales.backend.dao.mapper;

import com.bondsales.backend.common.SalesInfo;
import com.bondsales.backend.dao.entity.Sales;
import org.apache.ibatis.annotations.Mapper;

import java.util.Date;
import java.util.List;

@Mapper
public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sellid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    Sales selectByPrimaryKey(Long sellid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    List<Sales> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sales record);

    List<Sales> lookUp(SalesInfo salesInfo);
}