package com.bondsales.backend.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Sales implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALES.sellID
     *
     * @mbggenerated
     */
    private Long sellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALES.userID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALES.bondID
     *
     * @mbggenerated
     */
    private Long bondid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALES.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALES.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SALES
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALES.sellID
     *
     * @return the value of SALES.sellID
     *
     * @mbggenerated
     */
    public Long getSellid() {
        return sellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALES.sellID
     *
     * @param sellid the value for SALES.sellID
     *
     * @mbggenerated
     */
    public void setSellid(Long sellid) {
        this.sellid = sellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALES.userID
     *
     * @return the value of SALES.userID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALES.userID
     *
     * @param userid the value for SALES.userID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALES.bondID
     *
     * @return the value of SALES.bondID
     *
     * @mbggenerated
     */
    public Long getBondid() {
        return bondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALES.bondID
     *
     * @param bondid the value for SALES.bondID
     *
     * @mbggenerated
     */
    public void setBondid(Long bondid) {
        this.bondid = bondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALES.price
     *
     * @return the value of SALES.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALES.price
     *
     * @param price the value for SALES.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALES.date
     *
     * @return the value of SALES.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALES.date
     *
     * @param date the value for SALES.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sellid=").append(sellid);
        sb.append(", userid=").append(userid);
        sb.append(", bondid=").append(bondid);
        sb.append(", price=").append(price);
        sb.append(", date=").append(date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
